print ('Halo, selamat datang di aplikasi unfaedah')
nama = input('Coba masukan nama kamu disini \n')
usia = int(input('Lalu masukan usia kamu disini \n'))
alamat = input('Lalu masukan alamat kamu disini \n')
hobi = input('Coba masukan hobi kamu disini \n')