from os import *
system("cls")
print ('Halo, selamat datang di aplikasi unfaedah')
nama = input('Coba masukan nama kamu disini : \n')
usia = int(input('Lalu masukan usia kamu disini : \n'))
alamat = input('Lalu masukan alamat kamu disini : \n')
hobi = input('Hobi kamu apa ? \n')

s('cls')
print('Hallo ,' ,nama)
print('Oke jadi saya akan konfirmasi data kamu : \n')
print('Nama kamu adalah : ' ,nama)
print('Usia kamu adalah : ' ,usia)
print('Alamat kamu adalah : ' ,alamat)
print('Hobi kamu adalah : ' ,hobi)
input('Tekan enter untuk melanjutkan')